task: detection

num_classes: 3
remap_mscoco_category: False

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoXDetection
    img_folder: /home/cx/Projects/wen/dataSets/flir_align/images/train
    ann_file: /home/cx/Projects/wen/dataSets/flir_align/train.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 4
  num_workers: 4
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoXDetection
    img_folder: /home/cx/Projects/wen/dataSets/flir_align/images/test
    ann_file: /home/cx/Projects/wen/dataSets/flir_align/test.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 8
  num_workers: 4
  drop_last: False